name: peutzdesign
markdown: kramdown
highlighter: rouge
kramdown:
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
baseurl:
url: https://peutzdesign.com
img: https://peutzdesign.com/assets/images/
exclude: ['README.md', 'assets/svg/*.svg', "node_modules", "gulpfile.js", "package.json"]
permalink: pretty
sass:
  sass_dir: _scss
  style: compressed
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
collections:
  galleries:
  digital:
    output: true
    permalink: /digital/:path/
  interface:
    output: true
    permalink: /interface/:path/
  traditional:
    output: true
    permalink: /traditional/:path/
